[package]
name = "farm-analyze-lo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.44"
rust_decimal = "1.31"
rust_decimal_macros = "1.31"

[dev-dependencies]
rstest = "0.18.1"
